# Streamlit Cloud Secrets Configuration
# Copy this content to your Streamlit Cloud app's secrets.toml

# Supabase Database (FREE!)
SUPABASE_URL = "https://your-project-ref.supabase.co"
SUPABASE_KEY = "your-anon-public-key"

# Email Configuration (Optional)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "your-email@gmail.com"
SENDER_PASSWORD = "your-app-password"  # Gmail App Password

# App Configuration  
APP_URL = "https://your-app-name.streamlit.app"

# Setup Instructions:

# 1. Create FREE Supabase Account:
#    - Go to https://supabase.com
#    - Sign up (100% free)
#    - Create new project
#    - Copy URL and anon key from Settings > API

# 2. Set up Database:
#    - Go to SQL Editor in Supabase
#    - Run the SQL from supabase_integration.py

# 3. Deploy to Streamlit Cloud:
#    - Go to https://share.streamlit.io  
#    - Connect GitHub
#    - Deploy this repository
#    - Add these secrets in app settings

# 4. Gmail Setup (Optional):
#    - Enable 2-Factor Authentication
#    - Create "App Password" for email verification

# Cost Breakdown:
# Supabase FREE tier includes:
# ✅ 500MB database (enough for 1000s of users)
# ✅ Unlimited API requests
# ✅ Real-time subscriptions  
# ✅ Authentication built-in
# ✅ No credit card required

# Your app will use ~10-50MB max = STAYS FREE! 🎉