# Streamlit Cloud Secrets
# When you deploy, paste this content into your Streamlit Cloud app's secrets

# Replace with YOUR Supabase project details:
SUPABASE_URL = "https://uvsdbuonyfzajhtrgnxq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2c2RidW9ueWZ6YWpodHJnbnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNjUxNjgsImV4cCI6MjA3NjY0MTE2OH0.tq_dQfCIl68bSt2BUPP0lWW2DjjwPpxcKV6LIt2LRFg"

# Optional: Email settings (for password reset later)  
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "elderevilbencon@gmail.com"
SENDER_PASSWORD = "ggaa zjqv orcb jblp"
APP_URL = "https://your-app-name.streamlit.app"