# Local development secrets
# This file tells the app to use SQLite locally
# When you deploy to Streamlit Cloud, add your Supabase credentials there

# Leave these empty for local SQLite development:
SUPABASE_URL = "https://uvsdbuonyfzajhtrgnxq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2c2RidW9ueWZ6YWpodHJnbnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNjUxNjgsImV4cCI6MjA3NjY0MTE2OH0.tq_dQfCIl68bSt2BUPP0lWW2DjjwPpxcKV6LIt2LRFg"

# Optional: Add these later when you want email features
EMAIL_USERNAME = ""
EMAIL_PASSWORD = ""
APP_URL = "http://localhost:8504"