[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false
allowRunOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#8B4513"
backgroundColor = "#F4E4BC"
secondaryBackgroundColor = "#FFFACD"
textColor = "#8B4513"
base = "light"
